---
version: 2

registries:
  wefight-devs:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.PACKAGES_GITHUB_TOKEN}}

updates:
 - package-ecosystem: "terraform"
   directory: "."
   registries:
      - nomaddevops
   schedule:
     interval: "monthly"