
name: Tests 

on:
  pull_request:
    branches:
      - '*'

jobs:
  SyntaxCheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Terraform
      uses: little-core-labs/install-terraform@v2.0.0
      with:
          version: 1.6.3
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Terraform Checks
      run: |
        terraform init
        terraform validate
        terraform test

  SecurityChecks:
    needs: SyntaxCheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install TFSec
      run : |
        curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
        tfsec .