
name: Tests 

on:
  pull_request:
    branches:
      - '*'

jobs:
  SecurityChecks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Terraform
      uses: little-core-labs/install-terraform@v2.0.0
      with:
          version: 1.1.3

    - name: Terraform Checks
      run: |
        terraform init
        terraform validate
    - name: Install TFSec
      run : |
        curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
        tfsec .

